language: node_js
node_js:
  - "8"
  - "10"

# safelist
branches:
  only:
  - master

before_install:
  # yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn
  - yarn lint
  - yarn build:lib
  - yarn install:lib
  - yarn test:lib:schematics
  - yarn build:lib:schematics

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
